name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # or "master" depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --configuration production

    - name: Deploy to GitHub Pages
      run: npx angular-cli-ghpages --dir=dist/your-app-name
